name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - chemicalfun
  - xgems
  - thermofun=0.5.0
  - thermohubclient
  - pandas
  - chaospy
  - plotly
  - jmespath
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
    - openpyxl
