name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - chemicalfun
  - xgems
  - thermofun=0.5.0
  #- thermofun>=0.3.4
  - thermohubclient
#  - pandas=0.25.3
#  - beakerx=1.4.1
#  - spdlog>=1.10.0
  - jupyter
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
