name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - numpy
  - pip
  - thermofun=0.3.8
  - thermohubclient
  - pandas=0.25.3
  - beakerx=1.4.1
  - plotly
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
