name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.7.5
  - numpy
  - pip
  - thermofun>=0.3.4
  - thermohubclient
  - pandas=0.25.3
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
    - beakerx
