name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - chemicalfun=0.1.9=py310hd41b1e2_1
  - xgems=1.0.8=py310h3908379_0
  - thermofun=0.4.4=py310haded995_0
  #- thermofun>=0.3.4
  - thermohubclient
#  - pandas=0.25.3
#  - beakerx=1.4.1
#  - spdlog>=1.10.0
  - jupyter
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
