name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - thermofun
  - xgems=1.0.6
  - thermohubclient
  - pandas
  - chaospy
  - plotly
  - jmespath
  - pip:
    - matplotlib
    - IPython
    - voila
    - py4j
